[package]
name = "javap"
version = "0.1.0"
authors = ["Tim Detwiler <timdetwiler@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
classfile = { path = "../classfile", version = "0.1" }
log = "0.3.6"
env_logger = "0.3.3"

[dev-dependencies]
zip = "0.1.17"
